import { useState, type FormEvent } from 'react';
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import MenuItem from '@mui/material/MenuItem';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import { DeferredPhotoUpload } from '../../components/DeferredPhotoUpload';
import { deletePhoto, uploadPhoto } from '../../lib/photoUpload';
import type { IngredientUnit } from '../../types/ingredient';
import { INGREDIENT_UNITS } from './ingredientUnits';
import type { IngredientInput } from './api';

interface IngredientFormProps {
  initialValues?: IngredientInput;
  // The ingredient's own id — real, for an edit; freshly pre-generated by
  // the caller, for a create (see CreateIngredientDialog.tsx) — so a
  // staged photo can be uploaded (keyed by this id) at submit time, before
  // createIngredient/updateIngredient is ever called.
  ingredientId: string;
  submitLabel: string;
  onSubmit: (input: IngredientInput) => Promise<void>;
}

export function IngredientForm({ initialValues, ingredientId, submitLabel, onSubmit }: IngredientFormProps) {
  const [name, setName] = useState(initialValues?.name ?? '');
  const [quantity, setQuantity] = useState(initialValues?.quantity.toString() ?? '');
  const [unit, setUnit] = useState<IngredientUnit | ''>(initialValues?.unit ?? '');
  const [kcal, setKcal] = useState(initialValues?.kcal.toString() ?? '');
  const [photoUrl, setPhotoUrl] = useState<string | null>(initialValues?.photo_url ?? null);
  const [pendingPhotoFile, setPendingPhotoFile] = useState<File | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();
    if (!unit) return;
    setError(null);
    setSubmitting(true);
    try {
      const finalPhotoUrl = pendingPhotoFile
        ? await uploadPhoto(pendingPhotoFile, 'ingredient', ingredientId)
        : photoUrl;
      await onSubmit({
        name,
        quantity: Number(quantity),
        unit,
        kcal: Number(kcal),
        photo_url: finalPhotoUrl,
      });

      // Removing an existing photo (not just replacing it, and not the
      // create flow — initialValues.photo_url is only ever set on an
      // edit) also deletes its R2 object, not just the field. Runs after
      // the field update above succeeds, not before — deleting from R2
      // first and then having the actual save fail would leave the row
      // still pointing at a now-deleted object. Best-effort: an orphaned
      // object if this fails is the same accepted risk documented
      // elsewhere for this feature (docs/pending-deviations.md, Ticket 15).
      if (initialValues?.photo_url && !finalPhotoUrl) {
        try {
          await deletePhoto('ingredient', ingredientId);
        } catch {
          // Swallowed — see above.
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong. Try again.');
      setSubmitting(false);
    }
  }

  return (
    <Stack spacing={2.5} component="form" onSubmit={handleSubmit}>
      {error && <Alert severity="error">{error}</Alert>}

      <Box sx={{ display: 'flex', justifyContent: 'center' }}>
        <DeferredPhotoUpload
          photoUrl={photoUrl}
          onChange={setPhotoUrl}
          onFileSelected={setPendingPhotoFile}
          alt={name || 'ingredient'}
          size={120}
        />
      </Box>

      <TextField
        label="Name"
        value={name}
        onChange={(e) => setName(e.target.value)}
        required
        fullWidth
        autoFocus
      />
      <Stack direction="row" spacing={2}>
        <TextField
          label="Quantity"
          type="number"
          value={quantity}
          onChange={(e) => setQuantity(e.target.value)}
          required
          fullWidth
          slotProps={{ htmlInput: { min: 0, step: 0.01 } }}
        />
        <TextField
          label="Unit"
          select
          value={unit}
          onChange={(e) => setUnit(e.target.value as IngredientUnit)}
          required
          fullWidth
        >
          {INGREDIENT_UNITS.map((option) => (
            <MenuItem key={option} value={option}>
              {option}
            </MenuItem>
          ))}
        </TextField>
      </Stack>
      <TextField
        label="Kcal"
        type="number"
        value={kcal}
        onChange={(e) => setKcal(e.target.value)}
        required
        fullWidth
        slotProps={{ htmlInput: { min: 0, step: 0.1 } }}
      />
      <Button type="submit" variant="contained" size="large" disabled={submitting}>
        {submitting ? 'Saving…' : submitLabel}
      </Button>
    </Stack>
  );
}
